module.exports = {
  extends: ["stylelint-config-standard"],
  plugins: ["stylelint-order"],
  rules: {
    "order/properties-order": [
      [
        "position",
        "top",
        "right",
        "bottom",
        "left",
        "z-index",
        "display",
        "flex-direction",
        "justify-content",
        "align-items",
        "gap",
        "width",
        "height",
        "min-width",
        "min-height",
        "max-width",
        "max-height",
        "margin",
        "padding",
        "box-sizing",
        "font-family",
        "font-size",
        "font-weight",
        "line-height",
        "letter-spacing",
        "text-align",
        "text-transform",
        "text-decoration",
        "color",
        "background",
        "background-color",
        "border",
        "border-radius",
        "box-shadow",
        "opacity",
        "transition",
        "animation",
        "transform",
        "cursor",
        "pointer-events",
      ],
      { unspecified: "bottomAlphabetical" },
    ],
  },
};
